### ISSUE TITLE
Checklist of things to make sure aren't shit

### ISSUE THREAD

**Issue by davemackintosh** [Multicolour/1.0RC#2]
There's a lot that's shit about Waterline (unresolved bugs, weird bugs and even weirder features, etc) but here's a list of things to make sure; very specifically, aren't shit about the debut of 1.0.

- [ ] If there are join tables, make sure their names aren't stupidly long. If they are, give a *helpful* error message.
- [ ] Have *helpful* error messages when an error occurs while trying to write, migrate or sometimes even read data. `E_UNKNOWN` is a copout for errors that commonly occur.
- [ ] Don't use the infinitely annoying bad choice of `.get(string)` and `.request(string)` because that was stupid Dave. Just stupid Dave.

-- expect more --
